### ISSUE TITLE
我使用"Input Method Panel"让我的fcitx5在wayland ibus中运行

### ISSUE THREAD

**Issue by gqcdm** [openSUSE/Customize-IBus#20]
[Input Method Panel](https://extensions.gnome.org/extension/261/kimpanel/)
Customize IBus输出:GSettings schema org.freedesktop.ibus.panel not found

The settings of extension customize-ibus@hollowman.ml had an error:
```
Error: GSettings schema org.freedesktop.ibus.panel not found
```

Stack trace:
```
_init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:556:23
_bulidWidget@/home/cdm/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/prefs.js:68:28
_init@/home/cdm/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/prefs.js:59:12
CustomizeIBus@/home/cdm/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/prefs.js:47:3
buildPrefsWidget@/home/cdm/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/prefs.js:29:10
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by HollowMan6** [comment]
抱歉，Customize IBus 只支持自定义GNOME桌面下GNOME原生自带的IBus前端：https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/ibusCandidatePopup.js 

虽然没用过你所说的[Input Method Panel](https://extensions.gnome.org/extension/261/kimpanel/)，但是看了一下kimpanel https://fcitx-im.org/wiki/Kimpanel , 所以这个是Fcitx的一个GNOME前端插件吗？看报错也确实应该是你的电脑上没安装IBus。如果是用的Fcitx的话那就更不合适了，本插件只适用于IBus。

先关闭Issue了，如果还有问题欢迎继续comment。

**Comment by HollowMan6** [comment]
对了，你的标题我有点没看明白，”fcitx5在wayland ibus中运行“指的是什么，fcitx5和ibus共存吗？

**Comment by HollowMan6** [comment]
建议同一个系统只使用一个输入法框架，不然很容易产生冲突。

**Comment by gqcdm** [comment]
> 对了，你的标题我有点没看明白，”fcitx5在wayland ibus中运行“指的是什么，fcitx5和ibus共存吗？

gnome运行在wayland,使用[Input Method Panel](https://extensions.gnome.org/extension/261/kimpanel/)让fcitx5在ibus下使用

**Comment by gqcdm** [comment]
> 
我误解了

**Comment by HollowMan6** [comment]
> gnome运行在wayland,使用[Input Method Panel](https://extensions.gnome.org/extension/261/kimpanel/)让fcitx5在ibus下使用
>> 建议同一个系统只使用一个输入法框架，不然很容易产生冲突。

首先这个插件是自己实现了一个类：https://github.com/wengxt/gnome-shell-extension-kimpanel/blob/master/panel.js，跟GNOME原生的IBus前端没关系。

其次还是建议只用一种输入法框架，因为一般`Error: GSettings schema org.freedesktop.ibus.panel not found`是只有IBus没有被安装在系统里才会出现的报错，`org.freedesktop.ibus.panel` 是一个ibus的dbus接口。如果你非要让fcitx5和ibus共存的话，建议看看是不是得修复GNOME上游或者IBus本身的问题，与插件本身应该没太大关系。

**Comment by HollowMan6** [comment]
> 我误解了

OK 没关系 😂，其实我挺好奇你是现在电脑上只安装了Fcitx5，还是说Fcitx5和IBus同时安装了。

**Comment by HollowMan6** [comment]
fcitx5和ibus共存的话我之前也试过，好像也不会报`Error: GSettings schema org.freedesktop.ibus.panel not found`，但是这个插件我确实不知道没用过，不清楚用了之后如果共存的话会发生什么情况。
