### ISSUE TITLE
鎖定畫面被修改

### ISSUE THREAD

**Issue by Chans-exe** [openSUSE/Customize-IBus#24]
hi, 感謝你的努力與付出, 非常喜歡這個插件
我克隆了`Theme Hub`並使用了nord主題,
但是此主題會修改鎖定畫面主題, 直到我關掉ibus客製化主題

**Version (please complete the following information):**
 - Ubuntu 22.10
 - GNOME 43
 - IBus 1.5.27-2
 - Customize IBus 83

使用仿微軟也有同相的情況

**Comment by HollowMan6** [comment]
你好，感谢汇报这个BUG，我重写了一下加载主题的逻辑，现在应该master分支里的代码：https://github.com/openSUSE/Customize-IBus/blob/main/customize-ibus%40hollowman.ml/extension.js 可以修复这个问题。你如果希望尝鲜的话可以用上面网址的文件替换`~/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/extension.js`，然后注销重新登录即可。后续我继续测试看看没问题的话发布新版。

In case you don't understand some of the simplified Chinese:
Hi! Thanks for reporting this issue. I have just rewrote the theme loding code logic. Now https://github.com/openSUSE/Customize-IBus/blob/main/customize-ibus%40hollowman.ml/extension.js should be Okay. If you want to try it out, you can replace `~/.local/share/gnome-shell/extensions/customize-ibus@hollowman.ml/extension.js` with that, and relogin your user account. I will draft a new release later if there's no further issue related to this change.

**Comment by Chans-exe** [comment]
目前看來已經沒問題了！
