### ISSUE TITLE
ubuntu 22.04 Customize-IBus 可能会导致：lock系统后重新登录的卡死

### ISSUE THREAD

**Issue by burg1ar** [openSUSE/Customize-IBus#26]
ubuntu 22.04 Customize-IBus 可能会导致：lock系统后重新登录的卡死
对比了存在该插件和删除该插件时的情况，应该是该插件导致的
但是，我重新在虚拟机里尝试复现，发现是不能复现的，不清楚哪里出了问题

**Comment by HollowMan6** [comment]
你好！我目前使用的是Ubuntu 22.10，Customize-IBus v84。暂无法复现你说的问题，能否看看 `journalctl /usr/bin/gnome-shell -e`里有没有什么可疑的错误？最近确实处理了一个和锁屏有关的问题 https://github.com/openSUSE/Customize-IBus/issues/24 可以看看是否是该版本引入的，低版本的插件是否存在该问题？

**Comment by burg1ar** [comment]
重新复现了一下，并保存了日志，见：
[gnome-shell.log](https://github.com/openSUSE/Customize-IBus/files/10118976/gnome-shell.log)
复现测试起始时间：11月 30 10:52:05

**Comment by burg1ar** [comment]
对照日志，发现加载主题比较可疑，经过对比测试发现：当移除主题后，不会再出现上述问题。应该是主题加载导致的问题，麻烦确认一下，感谢。

**Comment by HollowMan6** [comment]
你好，刚刚将修复的commit push进了master分支，删去了一些旧的主题延迟加载代码（不知道会不会导致兼容性问题，但是看目前用GNOME3的人很少了，应该也不需要照顾了），你可以参考这里manually安装方法尝鲜帮忙看看问题是否已经解决。感谢！
https://github.com/openSUSE/Customize-IBus#linux

没问题的话后面发新版。

**Comment by HollowMan6** [comment]
好的，稍后发新版。
