### ISSUE TITLE
UI suggestion - add country flag emoji as language indicator in taskbar

### ISSUE THREAD

**Issue by luca-brambilla** [openSUSE/Customize-IBus#27]
**Is your feature request related to a problem? Please describe.**
I have many Gnome integration in the taskbar and it is difficult to see what keyboard I am using since it's indicated as just text. With a flag emoji it would be easier to understand.

**Describe the solution you'd like**
Add the option to switch from country codes to the relative country flag emoji, if available.

**Additional context**
Add the option to customize manually the flag to country correspondence, if necessary.

**Comment by HollowMan6** [comment]
Hi! That sounds nice! I would recommend you to file an issue at the gnome-shell upstream first to check if they are willing to implement that natively in GNOME. https://gitlab.gnome.org/GNOME/gnome-shell/-/issues Most of the features here in this plugin are those that gnome-shell decides not to implement.

If they are not, then later I will check ways to implement that, but I can't give any promises currently as I'm too busy to add new features.

**Comment by HollowMan6** [comment]
Closing as stale.
