### ISSUE TITLE
可以添加一个候选框置顶显示的设置项吗

### ISSUE THREAD

**Issue by IC-killer** [openSUSE/Customize-IBus#36]
我使用ibus-rime遇到这个异常[https://github.com/rime/ibus-rime/issues/185](https://github.com/rime/ibus-rime/issues/185)

请问这个插件可以实现候选框置顶吗，否则一些应用可能会遮盖候选框

**Comment by IC-killer** [comment]
customize-ibus的中英文状态提示是正常的，可以位于gnome插件todo.txt之上

**Comment by HollowMan6** [comment]
候选框应该默认就是置顶的才对，我感觉这个应该是GNOME-Shell的一个bug，相关代码应该在这：https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/ibusCandidatePopup.js 中英文状态提示当初就是模仿ibusCandidatePopup写的，如果正常的话可能是他们最近引入的变动导致了此Bug

**Comment by HollowMan6** [comment]
> 如果正常的话可能是他们最近引入的变动导致了此Bug

研究了一下他们的commit记录，应该是GNOME-Shell的这个PR引入的：https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2331 所以如果你有需求的话，烦请在此PR下用英语留言谈一谈你遇到的这个问题，或者在GNOME-Shell那里新开一个issue
