### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by hillwoodroc** [openSUSE/Customize-IBus#7]
我试了下最近版本的效果，很不错，基本上达到了设想中的设计效果，可以算是提前通过了。不过还是有进一步改进的余地。

比如原生主题是设计有翻页按钮，但是自定义主题就没有，而且模仿对象微软输入法也是有翻页按钮，我建议在以后的改进中可以加入这个功能。

还有就是向下兼容，这套扩展在旧版 gnome-shell 上工作不是太稳定。长效支持的发行版，诸如 openSUSE Leap, Debian stable 以及 Centos 等，这些长效支持的发行版都不会提供最新的 gnome ，所以也应该考虑下在这类发行版的支持。这类发行版的用户其实是相当多的。

能自带几个预设主题更好。

加载字体列表特别卡。

**Comment by HollowMan6** [comment]
@hillwoodroc 首先谢谢您的指导建议！

> 比如原生主题是设计有翻页按钮，但是自定义主题就没有，而且模仿对象微软输入法也是有翻页按钮，我建议在以后的改进中可以加入这个功能。

我猜您应该是直接使用的[IBus Theme Hub的仿微软输入法主题](https://github.com/IBus-Customize/IBus-Theme-Hub/tree/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft)，这款主题我是从[ibus-tweaker](https://github.com/tuberry/ibus-tweaker)扩展中直接导出的，该插件提供的主题确实是没有提供翻页按钮（[透明化处理了](https://github.com/IBus-Customize/IBus-Theme-Hub/blob/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft/Blue-Dark-%E7%A7%91%E6%8A%80%E8%93%9D-%E6%B7%B1%E8%89%B2-1A5FB4.css#L30-L41)）。但是我的[IBus Theme Tools](https://github.com/IBus-Customize/IBus-Theme-Tools)是支持从现有GNOME Shell主题[提取出翻页按钮的](https://github.com/IBus-Customize/IBus-Theme-Tools/blob/main/IBus-Theme.py#L183-L194)。

后续可以考虑为[IBus Theme Hub的仿微软输入法主题](https://github.com/IBus-Customize/IBus-Theme-Hub/tree/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft)增加翻页按钮。

如果是从GNOME Shell直接提取出来的主题理论上应该是能正常显示翻页按钮的，没有显示的话请检查插件里是不是把调页按钮关了（增加这个功能是因为有些用户直接使用键盘翻页，在这种情况下不需要调页按钮，而且有的主题调页按钮太大了有些碍眼） 。
![image](https://user-images.githubusercontent.com/43995067/122800882-0bff4a80-d2f6-11eb-8f18-df8b129ed3fe.png)

> 还有就是向下兼容，这套扩展在旧版 gnome-shell 上工作不是太稳定。长效支持的发行版，诸如 openSUSE Leap, Debian stable 以及 Centos 等，这些长效支持的发行版都不会提供最新的 gnome ，所以也应该考虑下在这类发行版的支持。这类发行版的用户其实是相当多的。

好的，可以考虑一些兼容性问题，目前的话是在使用GNOME 3.38.4的Ubuntu 21.04和Manjaro中，和使用GNOME40的openSUSE Tumbleweed以及Fedora rawhide中都进行了测试，都是能够比较完美地使用的，后续可以进行一些更老GNOME版本的适配。但是目前鉴于我学业上压力比较重，需要准备期末考试以及升学方面，所以这部分计划暂时先放到中期检查之后的那个Coding阶段做（大概7月下旬及之后），那时候时间稍微宽裕一些：）

> 能自带几个预设主题更好。

目前因为我是支持的直接导入css，所以我之前专门弄了[IBus Theme Hub](https://github.com/IBus-Customize/IBus-Theme-Hub)IBus 主题集合来预备存放[预设主题](https://github.com/HollowMan6/IBus-Theme-Hub/issues/1)，用户直接下载该仓库，选择对应的css即可使用。后续可以增加更多的预设主题。

> 加载字体列表特别卡。

我是直接调用的[Gtk.FontButton](https://github.com/HollowMan6/Customize-IBus/blob/main/customize-ibus%40hollowman.ml/prefs.js#L252-L268)来进行字体选择的，并没有进行自己的加载字体列表逻辑和算法的实现，需要改进的话恐怕得前往GTK上游。另外我电脑选择字体时倒还是可以，不算卡。

再次感谢指导！欢迎继续提意见，谢谢！

**Comment by HollowMan6** [comment]
https://github.com/IBus-Customize/IBus-Theme-Hub/commit/6d985ab35cd4f287d1435cc3c54e5ad5642473b1 为[IBus Theme Hub的仿微软输入法主题](https://github.com/IBus-Customize/IBus-Theme-Hub/tree/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft)增加了翻页按钮。

![](https://github.com/IBus-Customize/IBus-Theme-Hub/raw/main/%E4%BB%BF%E5%BE%AE%E8%BD%AFMicrosoft/img/eg-light.png)

现在该主题和微软输入法的样式几乎无异了

**Comment by hillwoodroc** [comment]
我个人来说其实更期待 gtk 版的 skin 支持，如果和 gjs 版的皮肤文件格式能兼容就更好了。

**Comment by HollowMan6** [comment]
> 我个人来说其实更期待 gtk 版的 skin 支持，

gtk 版的 skin 支持实际上之前就已经完成了，只需要首先安装一些[GTK主题](https://www.gnome-look.org/browse/cat/135/)，然后使用[IBus Theme Tools](https://github.com/IBus-Customize/IBus-Theme-Tools#%E9%9D%9Egnome%E6%A1%8C%E9%9D%A2)就可以进行GTK主题的混搭了。[这是教程](https://blog.csdn.net/qq_18572023/article/details/116331601#t8)。

> 如果和 gjs 版的皮肤文件格式能兼容就更好了。

关于 gtk 版的 skin 和 gjs 版的皮肤文件格式相互兼容，我觉得这是不太现实的，原因有二。

其一，因为GNOME中的IBus是用GJS直接实现了一个[GNOME独有的前端](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/ibusCandidatePopup.js)，而在非GNOME中则是IBus本身自己实现的自带的前端，两者前端的实现方式并不相同，所以要兼容是基本不太行的。

其二，gjs 版的皮肤文件格式是通过直接设定的[GNOME Shell主题](https://www.gnome-look.org/browse/cat/134/order/latest/) IBus前端部分样式来实现的，而 gtk 版的 skin 是使用的GTK主题来实现。GNOME Shell主题和GTK主题这两者实际上并不兼容，主题设计者一般都会将他们分开，参见：https://github.com/vinceliuice/vimix-gtk-themes/tree/master/src 。

**Comment by hillwoodroc** [comment]
我们这边讨论了一下，还是建议你尝试一下给 ibus gtk 提供一个 css 的功能。

**Comment by HollowMan6** [comment]
> 我们这边讨论了一下，还是建议你尝试一下给 ibus gtk 提供一个 css 主题的功能。

不好意思，我不太理解您说的ibus gtk 的 css主题功能指的具体是什么，可能是我上次的回答产生了歧义。

我上次主要是想表达，虽然gtk 版的和 gjs 版的样式都是css文件定义的，但是他们样式定义中类名和属性名称有很大的区别，所以不能相互直接转化，也就无法实现兼容了。

GTK主题本身也是由css文件定义的，参见 https://github.com/vinceliuice/vimix-gtk-themes/blob/master/src/gtk/4.0/gtk.css ，如果用户想要修改的话直接在现有的GTK主题中使用css语法即可修改成功。

我的 IBus Theme Tools 更换IBus GTK主题流程：https://blog.csdn.net/qq_18572023/article/details/116331601#t9

自定义GTK主题供IBus使用教程：https://github.com/openSUSE/IBus-Theme-Tools/blob/main/README_CN.md#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84gtk%E4%B8%BB%E9%A2%98

谢谢！

**Comment by hillwoodroc** [comment]
我们期望的 feature 是 ibus 自带一套独立的主题系统，意思是独立于 gtk theme 的主题。你的实现并没有脱离系统 gtk theme，gnome-shell 的主题的确做到了。
@qiangzhao @epico

**Comment by HollowMan6** [comment]
您的意思是做成像fcitx那样的主题管理吗？那确实有难度，我后面可以研究研究他们是怎么实现的。

**Comment by hillwoodroc** [comment]
你也可以参考一下 Firefox 设计。Firefox 虽然也用了 gtk3 ，但是主题系统是自己实现的一套。

**Comment by HollowMan6** [comment]
主题管理这部分可能需要更改ibus上游的代码了。把这个功能放到ibus-setup中可能最好。

**Comment by epico** [comment]
我觉得基于 Gtk Theme 挺好啊，根据已有的主题，在转换时，仅仅应用到 ibus panel 就可以了。

可以考虑将 Gtk Theme 和 ibus panel 共存，转换后的主题仅仅应用到 ibus panel 即可。

**Comment by hillwoodroc** [comment]
基于 gtk 主题，他现在其实已经做到了。

**Comment by HollowMan6** [comment]
Closing as most of the questions have been resolved.
